version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "seism0saurus"

  - package-ecosystem: "npm"
    directory: "/webapp/angular"
    schedule:
      interval: "weekly"
    reviewers:
      - "seism0saurus"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "seism0saurus"

  - package-ecosystem: "docker"
    directory: "/bot/containerimage"
    schedule:
      interval: "weekly"
    reviewers:
      - "seism0saurus"

  - package-ecosystem: "docker"
    directory: "/webapp/containerimage"
    schedule:
      interval: "weekly"
    reviewers:
      - "seism0saurus"
