version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "seism0saurus"

  - package-ecosystem: "npm"
    directory: "/webapp/angular"
    schedule:
      interval: "daily"
    reviewers:
      - "seism0saurus"
    groups:
      angular:
        patterns:
          - "@angular/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "seism0saurus"

  - package-ecosystem: "docker"
    directory: "/bot/containerimage"
    schedule:
      interval: "daily"
    reviewers:
      - "seism0saurus"

  - package-ecosystem: "docker"
    directory: "/webapp/containerimage"
    schedule:
      interval: "daily"
    reviewers:
      - "seism0saurus"
