name: "Build and deploy"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
    types: [ "closed" ]

jobs:
  build-shared:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build the shared part of the project
        run: mvn --batch-mode install --file shared/pom.xml
      - name: Archive shared jar
        uses: actions/upload-artifact@v3
        with:
          name: shared.jar
          path: /shared/target/shared-0.0.1-SNAPSHOT.jar
          retention-days: 1

  build-bot:
    runs-on: ubuntu-latest
    needs: build-shared
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Download shared jar
        uses: actions/download-artifact@v3
        with:
          name: shared.jar
      - name: Build the bot
        run: mvn --batch-mode --update-snapshots install --file bot/pom.xml
      - name: Archive bot jar
        uses: actions/upload-artifact@v3
        with:
          name: bot.jar
          path: /bot/target/bot-0.0.1-SNAPSHOT.jar
          retention-days: 1

  build-webapp:
    runs-on: ubuntu-latest
    needs: build-shared
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Download shared jar
        uses: actions/download-artifact@v3
        with:
          name: shared.jar
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.13.0
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: npm dependencies and Angular cli
        run: cd webapp/angular && npm install -g @angular/cli@15.2.10
      - name: Build the webapp
        run: mvn --batch-mode --update-snapshots install --file webapp/pom.xml
      - name: Archive webapp jar
        uses: actions/upload-artifact@v3
        with:
          name: bot.jar
          path: /webapp/target/webapp-0.0.1-SNAPSHOT.jar
          retention-days: 1

  build-bruteforcer:
    runs-on: ubuntu-latest
    needs: build-shared
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Download shared jar
        uses: actions/download-artifact@v3
        with:
          name: shared.jar
      - name: Build the bruteforcer
        run: mvn --batch-mode --update-snapshots install --file bruteforcer/pom.xml
